# This file was generated by GoReleaser. DO NOT EDIT.
cask "prgen" do
  desc ""
  homepage "https://github.com/lugen4ro/prgen"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prgen"

  on_macos do
    url "https://github.com/lugen4ro/prgen/releases/download/v0.3.0/prgen_0.3.0_darwin_all.tar.gz"
    sha256 "67c2ecd6527413af6abe833145e94d0a5b2b9511feb015c99a8ba5836ef87b4d"
  end

  on_linux do
    on_intel do
      url "https://github.com/lugen4ro/prgen/releases/download/v0.3.0/prgen_0.3.0_linux_amd64.tar.gz"
      sha256 "6eda575623a819997632db9265181e4aaa058670ccba137d60f9d1fe2202f399"
    end
    on_arm do
      url "https://github.com/lugen4ro/prgen/releases/download/v0.3.0/prgen_0.3.0_linux_arm64.tar.gz"
      sha256 "71e0b35bcd88657bd65a615679ff1564f013ed73f1d0ec2509264f3326429bbc"
    end
  end

  # No zap stanza required
end
