# This file was generated by GoReleaser. DO NOT EDIT.
cask "prgen" do
  desc ""
  homepage "https://github.com/lugen4ro/prgen"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prgen"

  on_macos do
    url "https://github.com/lugen4ro/prgen/releases/download/v0.2.0/prgen_0.2.0_darwin_all.tar.gz"
    sha256 "ba1b944a388feebc3f69672f7600e249777bf9e2b039b36cb4b819dafadea554"
  end

  on_linux do
    on_intel do
      url "https://github.com/lugen4ro/prgen/releases/download/v0.2.0/prgen_0.2.0_linux_amd64.tar.gz"
      sha256 "681e278499307629d60311ae28ab8b5aba06356e607a4d7e183fb572bae66a1f"
    end
    on_arm do
      url "https://github.com/lugen4ro/prgen/releases/download/v0.2.0/prgen_0.2.0_linux_arm64.tar.gz"
      sha256 "88072406512f72a13b380a00abe2fb2ad2eb2b9824364b02609e2f0c45e7174c"
    end
  end

  # No zap stanza required
end
