# This file was generated by GoReleaser. DO NOT EDIT.
cask "prgen" do
  desc ""
  homepage "https://github.com/lugen4ro/prgen"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "prgen"

  on_macos do
    url "https://github.com/lugen4ro/prgen/releases/download/v0.1.0/prgen_0.1.0_darwin_all.tar.gz"
    sha256 "5ab50ed5d706cc5c6d4ab786bc638e70e0f7fdb590b7f1b98f2e5e6ed1cb94e4"
  end

  on_linux do
    on_intel do
      url "https://github.com/lugen4ro/prgen/releases/download/v0.1.0/prgen_0.1.0_linux_amd64.tar.gz"
      sha256 "baf904e3c7186e4f7614b784e87091b82dda4d372396fecb7a9efa5b1118eb1d"
    end
    on_arm do
      url "https://github.com/lugen4ro/prgen/releases/download/v0.1.0/prgen_0.1.0_linux_arm64.tar.gz"
      sha256 "673144410b477dc3674d6109430e7f3cc150945e5bee43888138d078f51fa044"
    end
  end

  # No zap stanza required
end
